#!/bin/sh
#
# /etc/init.d/S99aesdsocket
#
### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $network $syslog
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop aesdsocket daemon
### END INIT INFO

NAME="aesdsocket"
DAEMON="/usr/bin/${NAME}"
PIDFILE="/var/run/${NAME}.pid"
DAEMON_OPTS="-d"

case "$1" in
    start)
        echo "Starting ${NAME}..."
        if [ -e "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
            echo "  ${NAME} is already running (PID $(cat "$PIDFILE"))."
            exit 0
        fi

        start-stop-daemon --start \
            --quiet \
            --pidfile "$PIDFILE" \
            --make-pidfile \
            --background \
            --exec "$DAEMON" -- $DAEMON_OPTS

        if [ $? -eq 0 ]; then
            echo "  ${NAME} started."
            exit 0
        else
            echo "  Failed to start ${NAME}!"
            exit 1
        fi
        ;;
    stop)
        echo "Stopping ${NAME}..."
        if [ -e "$PIDFILE" ]; then
            start-stop-daemon --stop \
                --quiet \
                --pidfile "$PIDFILE" \
                --retry TERM/5/KILL/2

            if [ $? -eq 0 ]; then
                rm -f "$PIDFILE"
                echo "  ${NAME} stopped."
                exit 0
            else
                echo "  Failed to stop ${NAME}!"
                exit 1
            fi
        else
            echo "  ${NAME} is not running (no PID file)."
            exit 0
        fi
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 2
        ;;
esac
